version: "3.8"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx:nginx
    env_file: .env
    ports:
      - '443:443'
    volumes:
      - wp:/var/www/
    #restart: on-failure
    #restart: always
    restart: unless-stopped
    networks:
      - inception-network
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:wordpress
    env_file: .env
    expose:
      - '9000'
    # restart: on-failure
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks:
      - inception-network
    volumes:
      - wp:/var/www/

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:mariadb
    env_file:  .env
    healthcheck:
      test: ["CMD", "mysqladmin", "-h", "localhost", "ping"]
      start_period: 5s
      interval: 5s
      timeout: 2s
      retries: "20"
    expose:
      - '3306'
    restart: unless-stopped
    networks:
      - inception-network
    volumes:
      - db:/var/lib/mysql

networks:
  inception-network:
    name: inception-network
    driver: bridge


volumes:
  wp:
    name: wp
    driver_opts:
      o: bind
      device: ${WORDPRESS_VOLUME}
      type: none
  db:
    name: db
    driver_opts:
      o: bind
      device: ${MARIADB_VOLUME}
      type: none


