version: "3.8"

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:nginx
    volumes:
    - "wordpress:/var/www/html/"
    restart: always
    #restart: unless-stopped
    networks:
      - "inception-network"
    ports:
      - '443:443'
    depends_on:
    - wordpress

  wordpress:
    container_name: wordpress
    env_file: .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:wordpress
    restart: always
    volumes:
    - "wordpress:/var/www/html/"
    networks:
      - "inception-network"
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    env_file:  .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:mariadb
    # healthcheck:
    # test: ["CMD", "mysqladmin", "-h", "localhost", "ping"]
    # start_period: 5s
    # interval: 5s
    # timeout: 2s
    # retries: 20
    restart: always
    volumes:
    - "db:/var/lib/mysql"
    networks:
      - "inception-network"

networks:
  docker-network:
    name: inception-network
    driver: bridge


volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      o: bind
      device: ${WORDPRESS_VOLUME}
      type: none
  db:
    driver: local
    name: db
    driver_opts:
      o: bind
      device: ${MARIADB_VOLUME}
      type: none
